# Generated by Django 4.2.7 on 2023-11-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventMember",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("role", models.TextField()),
            ],
            options={"db_table": "Event_Member", "managed": False,},
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("image_link", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "Events", "managed": False,},
        ),
        migrations.CreateModel(
            name="EventsCat",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField(unique=True)),
                ("description", models.TextField()),
                ("image_link", models.TextField()),
                ("color", models.TextField()),
            ],
            options={"db_table": "Events_Cat", "managed": False,},
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("email", models.TextField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("github_link", models.TextField(blank=True, null=True)),
                ("image_link", models.TextField()),
                ("linkedin_link", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
            ],
            options={"db_table": "Members", "managed": False,},
        ),
        migrations.CreateModel(
            name="MembersRole",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField(unique=True)),
                ("image_link", models.TextField()),
                ("color", models.TextField()),
            ],
            options={"db_table": "Members_Role", "managed": False,},
        ),
        migrations.CreateModel(
            name="Organisations",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                (
                    "poc_name",
                    models.TextField(blank=True, db_column="POC_name", null=True),
                ),
                (
                    "poc_contact",
                    models.IntegerField(blank=True, db_column="POC_contact", null=True),
                ),
                (
                    "poc_email",
                    models.TextField(
                        blank=True, db_column="POC_email", null=True, unique=True
                    ),
                ),
            ],
            options={"db_table": "Organisations", "managed": False,},
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("image_link", models.TextField()),
                ("title", models.TextField()),
                ("date_created", models.DateTimeField()),
                ("caption", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "Posts", "managed": False,},
        ),
        migrations.CreateModel(
            name="PrismaMigrations",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("checksum", models.CharField(max_length=64)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("migration_name", models.CharField(max_length=255)),
                ("logs", models.TextField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("applied_steps_count", models.IntegerField()),
            ],
            options={"db_table": "_prisma_migrations", "managed": False,},
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("role", models.TextField()),
            ],
            options={"db_table": "Project_Member", "managed": False,},
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("image_link", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "Projects", "managed": False,},
        ),
        migrations.CreateModel(
            name="ProjectsCat",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField(unique=True)),
                ("description", models.TextField()),
                ("image_link", models.TextField()),
                ("color", models.TextField()),
            ],
            options={"db_table": "Projects_Cat", "managed": False,},
        ),
    ]
