# Generated by Django 4.2.7 on 2023-11-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_calls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="eventmember", options={},),
        migrations.AlterModelOptions(name="events", options={},),
        migrations.AlterModelOptions(name="eventscat", options={},),
        migrations.AlterModelOptions(name="members", options={},),
        migrations.AlterModelOptions(name="membersrole", options={},),
        migrations.AlterModelOptions(name="organisations", options={},),
        migrations.AlterModelOptions(name="posts", options={},),
        migrations.AlterModelOptions(name="projectmember", options={},),
        migrations.AlterModelOptions(name="projects", options={},),
        migrations.AlterModelOptions(name="projectscat", options={},),
    ]
