# Generated by Django 4.2.7 on 2023-12-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_calls", "0002_alter_eventmember_options_alter_events_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="is_featured",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
